services:
  - type: web
    name: game-suggestions
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: game-suggestions-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: EMAIL_VERIFICATION_REQUIRED
        value: "False"
    plan: free

databases:
  - name: game-suggestions-db
    plan: free